export default {
    userLogged: 'userLogged',
    boy: 'boy',
    girl: 'girl',
    unknow: 'unknow',
    mother: 'mother',
    grandmother: 'grandmother',
    father: 'father',
    grandfather: 'grandfather',
    other: 'other',
    email: 'email',
    unauth: 'Unauthorized',
    facebook: 'facebook',
    kakao: 'kakao',
    permMaster: 'master',
    permView: 'view',
    requestPermissions: 'request-permissions',
    location: 'location',
    repeatActivity: 'repeat-activity',
    none: 'none',
    daily: 'daily',
    weekly: 'weekly',
    monthly: 'monthly',
    yearly: 'yearly',
    overview: 'overview'
}